name: C++ Testing

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - mkl_randint_test
  pull_request:
  workflow_dispatch:

jobs:

  gtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repostiory
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup packages
        uses: ./.github/actions/setup

      - name: Configure
        run: |
          pip install mkl-include==2021.4
          pip install mkl==2021.4
          pip install mkl-devel==2021.4
          pip install mkl_random==1.2.2
          pip install mkl-service==2.4.0
          pip install mkl-static==2021.4
          
          mkdir build
          cd build
          export _BLAS_INCLUDE_DIR=`python -c 'import os;import sysconfig;data=sysconfig.get_path("data");print(f"{data}{os.sep}include")'`
          export MKL_LIBS_DIR=`python -c 'import os;import sysconfig;data=sysconfig.get_path("data");print(f"{data}{os.sep}lib")'`
          
          ls ${MKL_LIBS_DIR} | grep -i mkl
          
          Torch_DIR=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'` cmake .. -GNinja -DBUILD_TEST=ON -DWITH_COV=ON -DCMAKE_BUILD_TYPE=DEBUG -DUSE_MKL_BLAS=ON -DBLAS_INCLUDE_DIR=$_BLAS_INCLUDE_DIR -DMKL_LIBS_DIR=${MKL_LIBS_DIR}
          
          unset _BLAS_INCLUDE_DIR
          cd ..

      - name: Build
        run: |
          cd build
          cmake --build .
          cd ..

      - name: Check lib
        if: ${{ failure() }}
        run: |
          strings /home/runner/work/pyg-lib/pyg-lib/build/libpyg.so | grep -i viRng
          readelf -Ws /home/runner/work/pyg-lib/pyg-lib/build/libpyg.so | grep viRng


      - name: Run tests
        run: |
          cd build
          ctest --verbose --output-on-failure
          cd ..

      - name: Collect coverage
        run: |
          sudo apt-get install lcov
          lcov --directory . --capture --output-file .coverage.info
          lcov --remove .coverage.info '*/test/*' --output-file .coverage.info

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: .coverage.info
          fail_ci_if_error: false
