name: C++ Testing

on: [workflow_dispatch]

jobs:

  gtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repostiory
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup packages
        uses: ./.github/actions/setup

      - name: Configure
        run: |
          pip install mkl-include==2023.0.0
          
          cat /opt/hostedtoolcache/Python/3.8.16/x64/include/mkl_vsl_functions.h | grep viRngUniform
          echo "Code in mkl.h :"
          cat /opt/hostedtoolcache/Python/3.8.16/x64/include/mkl.h
          mkdir build
          cd build
          export _BLAS_INCLUDE_DIR=`python -c 'import os;import sysconfig;data=sysconfig.get_path("data");print(f"{data}{os.sep}include")'`
          Torch_DIR=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'` cmake .. -GNinja -DBUILD_TEST=ON -DWITH_COV=ON -DCMAKE_BUILD_TYPE=DEBUG -DUSE_MKL_BLAS=ON -DBLAS_INCLUDE_DIR=$_BLAS_INCLUDE_DIR
          unset _BLAS_INCLUDE_DIR
          cd ..

      - name: Build
        run: |
          cd build
          cmake --build .
          cd ..
      - name: My backup
        if: ${{ failure() }}
        run: |
           find /home -name libpyg.so

      - name: Run tests
        run: |
          cd build
          ctest --verbose --output-on-failure
          cd ..

      - name: Collect coverage
        run: |
          sudo apt-get install lcov
          lcov --directory . --capture --output-file .coverage.info
          lcov --remove .coverage.info '*/test/*' --output-file .coverage.info

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: .coverage.info
          fail_ci_if_error: false
